{% set name = "pyampute" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyampute-{{ version }}.tar.gz
  sha256: 19525e5c67c320540670a33497424578dcb976bc699508db56f31b079ed3c7f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy >=1.19.0
    - scipy
    - matplotlib-base >=3.4.0
    - scikit-learn

test:
  imports:
    - pyampute
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Transformer for generating multivariate missingness in complete datasets
  home: https://github.com/RianneSchouten/pyampute
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - wxicu
